import { Dimensions, StyleSheet } from "react-native";

const { width: screenWidth } = Dimensions.get("window");
export const theme = {
    colors: {
        background: "#FFFFFF",
        surface: "#FFFFFF",
        primary: "#2563EB",
        success: "#10B981",
        text: "#0F172A",
        muted: "#6B7280",
    },
    spacing: {
        page: 20,
        card: 12,
    },
    cardWidth: Math.min(300, Math.round(screenWidth * 0.72)),
};

const cardWidth = theme.cardWidth;

export default StyleSheet.create({
    appContainer: {
        flex: 1,
        backgroundColor: theme.colors.background,
    },
    pagePadding: {
        paddingHorizontal: theme.spacing.page,
    },
    headerRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    card: {
        backgroundColor: theme.colors.surface,
        borderRadius: 16,
        overflow: "hidden",
    },
    // small reusable styles used across screens
    centered: { justifyContent: "center", alignItems: "center" },

    // --- merged styles from app/(tabs)/index.styles.ts ---
    container: {
        flex: 1,
        backgroundColor: "white",
    },
    header: {
        backgroundColor: "white",
        paddingTop: 48,
        paddingBottom: 10,
        paddingHorizontal: 16,
    },
    balanceBadge: {
        backgroundColor: "rgba(255,255,255,0.2)",
        borderColor: "black",
        borderWidth: 1,
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 8,
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    countdownBanner: {
        backgroundColor: "rgba(255,255,255,0.1)",
        borderRadius: 18,
        padding: 16,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        borderColor: "black",
        borderWidth: 1,
    },
    featuredTitleRow: {
        paddingHorizontal: 16,
        marginBottom: 12,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    featuredScrollContainer: {
        paddingHorizontal: 12,
        paddingVertical: 6,
    },
    cardImage: {
        width: "100%",
        height: 160,
    },
    rewardBadge: {
        position: "absolute",
        top: 12,
        right: 12,
        backgroundColor: "#10B981",
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 6,
        flexDirection: "row",
        alignItems: "center",
    },
    cardContent: {
        padding: 14,
    },
    cardType: {
        color: "#6B7280",
        fontSize: 12,
        fontWeight: "600",
        marginBottom: 6,
    },
    cardTitle: {
        color: "#0F172A",
        fontSize: 16,
        fontWeight: "700",
        marginBottom: 8,
    },
    cardInfoRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    infoLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    infoText: {
        color: "#6B7280",
        fontSize: 12,
    },
    categoryContainer: {
        paddingHorizontal: 20,
        paddingBottom: 16,
    },
    categoryCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 14,
        overflow: "hidden",
        width: (screenWidth - 64) / 2,
        minWidth: 140,
        elevation: 2,
        shadowColor: "#000",
        shadowOpacity: 0.04,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 8,
    },
    categoryImage: {
        width: "100%",
        height: 110,
    },
    categoryOverlay: {
        position: "absolute",
        inset: 0,
    },
    categoryContent: {
        padding: 12,
    },
    categoryTitle: {
        fontSize: 14,
        fontWeight: "700",
        color: "#0F172A",
        marginBottom: 6,
    },
    statsWrapper: {
        paddingHorizontal: 20,
        marginBottom: 24,
    },
    statsCardLarge: {
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        paddingVertical: 20,
        paddingHorizontal: 18,
        elevation: 4,
        shadowColor: "#000",
        shadowOpacity: 0.06,
        shadowOffset: { width: 0, height: 8 },
        shadowRadius: 18,
    },
    statsGridLarge: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
    },
    statBlock: {
        width: "48%",
        alignItems: "center",
        paddingVertical: 16,
    },
    statIcon: {
        width: 44,
        height: 44,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 8,
    },
    statNumberLarge: {
        fontSize: 20,
        fontWeight: "700",
        color: "#0F172A",
    },
    statLabelSmall: {
        fontSize: 12,
        color: "#6B7280",
        marginTop: 6,
        textAlign: "center",
    },
    statsSmallContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        paddingHorizontal: 20,
        gap: 12,
        marginBottom: 12,
    },
    statsSmallCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        overflow: "hidden",
        width: (Dimensions.get("window").width - 64) / 2,
        minHeight: 110,
        elevation: 2,
        shadowColor: "#000",
        shadowOpacity: 0.04,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 8,
        padding: 12,
        justifyContent: "space-between",
    },
    statsSmallTop: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    statsSmallIconWrapper: {
        width: 44,
        height: 44,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
    },
    statsSmallNumber: {
        fontSize: 18,
        fontWeight: "700",
        color: "#0F172A",
        marginTop: 8,
    },
    statsSmallLabel: {
        color: "#6B7280",
        fontSize: 12,
        marginTop: 4,
    },
    modalContainer: {
        backgroundColor: "#FFFFFF",
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        paddingHorizontal: 20,
        paddingTop: 18,
        paddingBottom: 28,
        maxHeight: 520,
        elevation: 8,
        shadowColor: "#000",
        shadowOpacity: 0.12,
        shadowOffset: { width: 0, height: -6 },
        shadowRadius: 20,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: "700",
        color: "#0F172A",
        textAlign: "left",
    },
    modalSubtitle: {
        fontSize: 13,
        color: "#6B7280",
        marginTop: 6,
        marginBottom: 12,
    },
    modalContent: {
        paddingTop: 8,
    },
    gameInfo: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        marginBottom: 16,
    },
    gameImage: {
        width: 72,
        height: 72,
        borderRadius: 12,
        overflow: "hidden",
    },
    gameDetails: {
        flex: 1,
        justifyContent: "center",
    },
    gameTitle: {
        fontSize: 16,
        fontWeight: "700",
        color: "#0F172A",
        marginBottom: 4,
    },
    gameType: {
        fontSize: 12,
        color: "#6B7280",
    },
    modalActions: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 8,
    },
    cancelButton: {
        flex: 1,
        marginRight: 10,
        backgroundColor: "#F3F4F6",
        paddingVertical: 12,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    confirmButton: {
        flex: 1,
        marginLeft: 0,
        backgroundColor: "#2563EB",
        paddingVertical: 12,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    cancelButtonText: {
        color: "#0F172A",
        fontWeight: "700",
    },
    confirmButtonText: {
        color: "#FFFFFF",
        fontWeight: "700",
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.45)",
        justifyContent: "flex-end",
    },
    playButton: {
        backgroundColor: "#EFF6FF",
        borderRadius: 999,
        padding: 8,
        alignItems: "center",
        justifyContent: "center",
        width: 36,
        height: 36,
        shadowColor: "#000",
        shadowOpacity: 0.03,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 6,
        elevation: 2,
    },
});