import { Dimensions, StyleSheet } from "react-native";

const tintColorLight = '#0a7ea4';
const tintColorDark = '#fff';
export const reownGreen = '#008847';
export const reownOrange = '#FF573B';
export const reownBlue = '#0988F0';
export const reownGray = '#6C6C6C';
export const reownDarkGray = '#202020';

const { width: screenWidth } = Dimensions.get("window");
export const theme = {
    colors: {
        background: "#FFFFFF",
        surface: "#FFFFFF",
        primary: "#2563EB",
        success: "#10B981",
        text: "#0F172A",
        muted: "#6B7280",
    },
    spacing: {
        page: 10,
        card: 12,
    },
    cardWidth: Math.min(300, Math.round(screenWidth * 0.72)),
};

const cardWidth = theme.cardWidth;

export default StyleSheet.create({

    titleContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
    },
    reownLogo: {
        height: 48,
        width: 180,
    },
    appKitButtonContainer: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    appKitButton: {
        backgroundColor: reownOrange,
    },
    headerText: {
        fontFamily: 'KHTekaMono',
        fontSize: 14,
        lineHeight: 24,
        fontWeight: '600',
        color: '#fff',
    },
    headerContainer: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 16,
    },
    leftColumn: {
        flexDirection: 'column',
        width: '50%',
        height: '100%',
        justifyContent: 'flex-end',
        gap: 10,
    },

    appContainer: {
        flex: 1,
        backgroundColor: theme.colors.background
    },
    pagePadding: {
        paddingHorizontal: theme.spacing.page,
        backgroundColor: theme.colors.background,
    },
    headerRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    // Toggle / Tabs (Global Winners / Your Position)
    tabToggleContainer: {
        flexDirection: "row",
        backgroundColor: "#FFFFFF",
        marginHorizontal: 16,
        marginTop: 16,
        marginBottom: 8,
        borderRadius: 14,
        elevation: 2,
        shadowColor: "#000",
        shadowOpacity: 0.04,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 8,
        overflow: "hidden",
    },
    tabToggle: {
        flex: 1,
        paddingVertical: 12,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 12,
    },
    tabToggleActive: {
        backgroundColor: theme.colors.primary,
    },
    tabToggleText: {
        fontWeight: "700",
        color: "#6B7280",
    },
    tabToggleTextActive: {
        fontWeight: "700",
        color: "#FFFFFF",
    },
    card: {
        backgroundColor: theme.colors.surface,
        borderRadius: 16,
        overflow: "hidden",
        borderWidth: 1,
        borderColor: "white",
        elevation: 2,
        shadowColor: "#000",
        shadowOpacity: 0.04,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 8,
    },
    centered: { justifyContent: "center", alignItems: "center" },

    // merged styles from previous index.styles
    container: {
        flex: 1,
        backgroundColor: "white",
    },
    header: {
        backgroundColor: "white",
        paddingTop: 48,
        paddingBottom: 10,
        paddingHorizontal: 16,
    },
    balanceBadge: {
        backgroundColor: "rgba(255,255,255,0.2)",
        borderColor: "black",
        // borderWidth: 1,
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 8,
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    countdownBanner: {
        backgroundColor: "rgba(255,255,255,0.1)",
        borderRadius: 18,
        padding: 16,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        borderColor: "black",
        borderWidth: 1,
    },
    featuredTitleRow: {
        paddingHorizontal: 16,
        marginBottom: 12,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    featuredScrollContainer: {
        paddingHorizontal: 12,
        paddingVertical: 6,
    },
    cardImage: {
        width: "100%",
        height: 160,
    },
    rewardBadge: {
        position: "absolute",
        top: 12,
        right: 12,
        backgroundColor: "#10B981",
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 6,
        flexDirection: "row",
        alignItems: "center",
    },
    cardContent: {
        padding: 14,
    },
    cardType: {
        color: "#6B7280",
        fontSize: 12,
        fontWeight: "600",
        marginBottom: 6,
    },
    cardTitle: {
        color: "#0F172A",
        fontSize: 16,
        fontWeight: "700",
        marginBottom: 8,
    },
    cardInfoRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    infoLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    infoText: {
        color: "#6B7280",
        fontSize: 12,
        textAlign: "center",
    },
    categoryContainer: {
        paddingHorizontal: 20,
        paddingBottom: 16,
    },
    categoryCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 14,
        overflow: "hidden",
        width: (screenWidth - 36) / 2,
        minWidth: 140,
        elevation: 2,
        shadowColor: "#000",
        shadowOpacity: 0.04,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 8,
    },
    categoryImage: {
        width: "100%",
        height: 110,
    },
    categoryOverlay: {
        position: "absolute",
        inset: 0,
    },
    categoryContent: {
        padding: 12,
    },
    categoryTitle: {
        fontSize: 14,
        fontWeight: "700",
        color: "#0F172A",
        marginBottom: 6,
    },
    statsWrapper: {
        paddingHorizontal: 1,
        marginBottom: 24,
    },
    statsCardLarge: {
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        paddingVertical: 20,
        paddingHorizontal: 18,
        elevation: 4,
        shadowColor: "#000",
        shadowOpacity: 0.06,
        shadowOffset: { width: 0, height: 8 },
        shadowRadius: 18,
    },
    statsGridLarge: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
    },
    statBlock: {
        width: "48%",
        alignItems: "center",
        paddingVertical: 16,
    },
    statIcon: {
        width: 44,
        height: 44,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 8,
    },
    statNumberLarge: {
        fontSize: 20,
        fontWeight: "700",
        color: "#0F172A",
    },
    statLabelSmall: {
        fontSize: 12,
        color: "#6B7280",
        marginTop: 6,
        textAlign: "center",
    },
    statsSmallContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        paddingHorizontal: 20,
        gap: 12,
        marginBottom: 12,
    },
    statsSmallCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        overflow: "hidden",
        width: (Dimensions.get("window").width - 64) / 2,
        minHeight: 110,
        elevation: 2,
        shadowColor: "#000",
        shadowOpacity: 0.04,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 8,
        padding: 12,
        justifyContent: "space-between",
    },
    statsSmallTop: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    statsSmallIconWrapper: {
        width: 44,
        height: 44,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
    },
    statsSmallNumber: {
        fontSize: 18,
        fontWeight: "700",
        color: "#0F172A",
        marginTop: 8,
    },
    statsSmallLabel: {
        color: "#6B7280",
        fontSize: 12,
        marginTop: 4,
    },
    modalContainer: {
        backgroundColor: "#FFFFFF",
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        paddingHorizontal: 20,
        paddingTop: 18,
        paddingBottom: 28,
        maxHeight: 520,
        elevation: 8,
        shadowColor: "#000",
        shadowOpacity: 0.12,
        shadowOffset: { width: 0, height: -6 },
        shadowRadius: 20,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: "700",
        color: "#0F172A",
        textAlign: "left",
    },
    modalSubtitle: {
        fontSize: 13,
        color: "#6B7280",
        marginTop: 6,
        marginBottom: 12,
    },
    modalContent: {
        paddingTop: 8,
    },
    gameInfo: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        marginBottom: 16,
    },
    gameImage: {
        width: 72,
        height: 72,
        borderRadius: 12,
        overflow: "hidden",
    },
    gameDetails: {
        flex: 1,
        justifyContent: "center",
    },
    gameTitle: {
        fontSize: 16,
        fontWeight: "700",
        color: "#0F172A",
        marginBottom: 4,
    },
    gameType: {
        fontSize: 12,
        color: "#6B7280",
    },
    modalActions: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 8,
    },
    cancelButton: {
        flex: 1,
        marginRight: 10,
        backgroundColor: "#F3F4F6",
        paddingVertical: 12,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    confirmButton: {
        flex: 1,
        marginLeft: 0,
        backgroundColor: "#2563EB",
        paddingVertical: 12,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    cancelButtonText: {
        color: "#0F172A",
        fontWeight: "700",
    },
    confirmButtonText: {
        color: "#FFFFFF",
        fontWeight: "700",
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.45)",
        justifyContent: "flex-end",
    },
    playButton: {
        backgroundColor: "#EFF6FF",
        borderRadius: 999,
        padding: 8,
        alignItems: "center",
        justifyContent: "center",
        width: 36,
        height: 36,
        shadowColor: "#000",
        shadowOpacity: 0.03,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 6,
        elevation: 2,
    },
    searchBar: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255,255,255,0.12)",
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 8,
        marginBottom: 12,
    },
    difficultyPill: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 999,
        overflow: "hidden",
    },
    difficultyEasy: { backgroundColor: "#ECFDF5" },
    difficultyMedium: { backgroundColor: "#FFFBEB" },
    difficultyHard: { backgroundColor: "#FEF2F2" },
    difficultyTextEasy: { color: "#065F46", fontSize: 12, fontWeight: "600" },
    difficultyTextMedium: { color: "#92400E", fontSize: 12, fontWeight: "600" },
    difficultyTextHard: { color: "#991B1B", fontSize: 12, fontWeight: "600" },
    mostPlayedCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        overflow: "hidden",
        width: 160,
        elevation: 2,
        shadowColor: "#000",
        shadowOpacity: 0.04,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 8,
    },
    // Leaderboard / Ranks
    leaderboardItem: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 14,
        marginBottom: 12,
        elevation: 2,
        shadowColor: "#000",
        shadowOpacity: 0.04,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 8,
    },
    rankBadge: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: "center",
        justifyContent: "center",
        marginRight: 12,
    },
    rankNumberText: {
        fontWeight: "700",
        color: "#2563EB",
    },
    avatarWrapper: {
        marginRight: 12,
    },
    avatarImage: {
        width: 40,
        height: 40,
        borderRadius: 20,
    },
    leaderboardInfo: {
        flex: 1,
    },
    leaderboardTitle: {
        fontSize: 16,
        fontWeight: "700",
        color: "#0F172A",
    },
    leaderboardSubtitleRow: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 6,
    },
    leaderboardSubtitleText: {
        color: "#6B7280",
        fontSize: 12,
        marginLeft: 6,
    },
    leaderboardStats: {
        alignItems: "flex-end",
    },
    leaderboardReward: {
        fontWeight: "700",
        color: "#0F172A",
    },
    leaderboardStreak: {
        fontSize: 12,
        color: "#2563EB",
        marginTop: 6,
    },
    // Leaderboard Rewards Card
    rewardsCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        padding: 18,
        marginBottom: 16,
        elevation: 3,
        shadowColor: "#000",
        shadowOpacity: 0.04,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 12,
    },
    rewardsTitle: {
        fontSize: 16,
        fontWeight: "700",
        color: "#0F172A",
        marginBottom: 12,
    },
    rewardsRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 12,
    },
    rewardItem: {
        alignItems: "center",
        flex: 1,
    },
    rewardIconWrapper: {
        width: 48,
        height: 48,
        borderRadius: 24,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 8,
    },
    rewardLabel: {
        fontWeight: "700",
        color: "#0F172A",
        textAlign: "center",
    },
    rewardAmount: {
        color: "#10B981",
        fontWeight: "700",
        marginTop: 4,
    },
    rewardsDivider: {
        height: 1,
        backgroundColor: "#F3F4F6",
        marginVertical: 12,
    },
    // Personal ranking / Your Position card
    personalCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        padding: 18,
        alignItems: "center",
        elevation: 2,
        shadowColor: "#000",
        shadowOpacity: 0.04,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 12,
    },
    personalAvatarCircle: {
        width: 96,
        height: 96,
        borderRadius: 48,
        backgroundColor: "#EFF6FF",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 12,
    },
    personalRank: {
        fontSize: 22,
        fontWeight: "700",
        color: "#0F172A",
        marginBottom: 6,
    },
    personalSubtitle: {
        color: "#6B7280",
        marginBottom: 12,
    },
    progressContainer: {
        width: "100%",
        marginBottom: 12,
    },
    progressHeaderRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 6,
    },
    progressLabel: {
        color: "#6B7280",
    },
    progressTarget: {
        fontWeight: "700",
        color: "#0F172A",
    },
    progressBarBackground: {
        height: 8,
        backgroundColor: "#F3F4F6",
        borderRadius: 999,
        overflow: "hidden",
    },
    progressBarFill: {
        height: "100%",
        backgroundColor: theme.colors.primary,
        borderRadius: 999,
    },
    personalStatsRow: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 8,
    },
    statPill: {
        flex: 1,
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 10,
        alignItems: "center",
        justifyContent: "center",
        marginRight: 8,
    },
    statPillNumber: {
        fontSize: 20,
        fontWeight: "700",
        color: "#0F172A",
        marginTop: 8,
    },
    statPillLabel: {
        color: "#6B7280",
        fontSize: 12,
        textAlign: "center",
        marginTop: 4,
    },
    // Profile screen styles
    profileCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        padding: 18,
        alignItems: "center",
        elevation: 3,
        shadowColor: "#000",
        shadowOpacity: 0.04,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 12,
        marginBottom: 16,
    },
    profileAvatar: {
        width: 96,
        height: 96,
        borderRadius: 48,
        overflow: "hidden",
    },
    avatarEditButton: {
        position: "absolute",
        right: 0,
        bottom: 0,
        backgroundColor: theme.colors.primary,
        borderRadius: 20,
        padding: 8,
        borderWidth: 2,
        borderColor: "#FFFFFF",
    },
    avatarOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        borderRadius: 48,
        backgroundColor: "rgba(0,0,0,0.35)",
        alignItems: "center",
        justifyContent: "center",
    },
    profileName: {
        fontSize: 18,
        fontWeight: "700",
        color: "#0F172A",
        marginTop: 12,
    },
    profileSince: {
        color: "#6B7280",
        marginTop: 4,
    },
    profileStatsContainer: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-around",
        marginTop: 16,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: "#F3F4F6",
    },
    profileStatItem: {
        alignItems: "center",
    },
    profileStatNumber: {
        fontSize: 18,
        fontWeight: "700",
        color: "#0F172A",
    },
    profileStatLabel: {
        color: "#6B7280",
        fontSize: 12,
        marginTop: 4,
    },
    profileDetailsCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        padding: 16,
        elevation: 2,
        shadowColor: "#000",
        shadowOpacity: 0.04,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 12,
    },
    profileDetailRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 12,
    },
    profileDetailLabel: {
        marginLeft: 8,
        fontWeight: "600",
        color: "#0F172A",
    },
    profileDetailValue: {
        color: "#6B7280",
        marginLeft: 8,
    },
    // Payment history items
    paymentHistoryContainer: {
        paddingHorizontal: 1,
        marginTop: 24,
        marginBottom: 32,
    },
    paymentItem: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        backgroundColor: "#FFFFFF",
        padding: 14,
        borderRadius: 12,
        marginBottom: 12,
        elevation: 1,
        shadowColor: "#000",
        shadowOpacity: 0.03,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 6,
    },
    paymentItemLeft: {
        flex: 1,
    },
    paymentItemGame: {
        fontSize: 14,
        fontWeight: "700",
        color: "#0F172A",
    },
    paymentItemDate: {
        color: "#6B7280",
        fontSize: 12,
        marginTop: 6,
    },
    paymentItemAmountPositive: {
        fontWeight: "700",
        color: "#10B981",
    },
    paymentItemAmountNegative: {
        fontWeight: "700",
        color: "#2563EB",
    },
    paymentStatusFailed: {
        color: "#DC2626",
        fontSize: 12,
        fontWeight: "600",
        marginTop: 6,
    },
    paymentTxHash: {
        color: "#6B7280",
        fontSize: 12,
        marginTop: 4,
    },
    awaitingPaymentContainer: {
        backgroundColor: "#FFFBEB",
        borderRadius: 16,
        padding: 16,
        marginTop: 16,
    },
    awaitingPaymentHeading: {
        fontSize: 16,
        fontWeight: "700",
        color: "#92400E",
        marginBottom: 12,
    },
    awaitingPaymentHelper: {
        color: "#B45309",
        fontSize: 12,
        marginBottom: 8,
    },
    awaitingPaymentItem: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: "#FDE68A",
    },
    awaitingPaymentLeft: {
        flex: 1,
        paddingRight: 12,
    },
    awaitingPaymentStatus: {
        marginTop: 4,
        color: "#B45309",
        fontSize: 12,
    },
    awaitingPaymentAmount: {
        color: "#B45309",
        fontWeight: "700",
    },
    awaitingPaymentTime: {
        color: "#B45309",
        fontSize: 12,
        marginTop: 4,
    },
    awaitingPaymentHintRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "flex-end",
        marginTop: 4,
    },
    awaitingPaymentHint: {
        color: "#B45309",
        fontSize: 12,
        fontWeight: "600",
    },
    awaitingPaymentSending: {
        color: "#92400E",
        fontSize: 12,
        fontWeight: "700",
    },
    // How to Improve Your Rank
    howToCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        padding: 18,
        elevation: 2,
        shadowColor: "#000",
        shadowOpacity: 0.04,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 12,
        marginBottom: 12,
    },
    howToTitle: {
        fontSize: 16,
        fontWeight: "700",
        color: "#0F172A",
        marginBottom: 8,
    },
    howToList: {
        gap: 12,
    },
    howToItem: {
        flexDirection: "row",
        alignItems: "flex-start",
        paddingVertical: 6,
    },
    howToIcon: {
        width: 36,
        height: 36,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
        marginRight: 12,
    },
    howToTextContainer: {
        flex: 1,
    },
    howToItemTitle: {
        fontWeight: "700",
        color: "#0F172A",
    },
    howToItemDesc: {
        color: "#6B7280",
        fontSize: 13,
        marginTop: 4,
    },
});
